Repository linode/linodego, pull requests merged in 2020-10, with the labels that each got.

#166 add BYO SSL support for Object Storage
  account_invoices.go
  client.go
  domain_records.go
  firewall_devices.go
  firewall_rules.go
  instance_configs.go
  instance_disks.go
  instance_ips.go
  instance_snapshots.go
  instance_stats.go
  instance_volumes.go
  lke_cluster_pools.go
  lke_clusters.go
  nodebalancer_config_nodes.go
  nodebalancer_configs.go
  nodebalancer_stats.go
  object_storage_bucket_certs.go
  resources.go
  resources_test.go
  test/integration/fixtures/TestObjectStorageBucketCert.yaml
  test/integration/object_storage_bucket_certs_test.go
Labels: added-feature

#165 make ClusterConditionFunc's adhere to k8s waiter convention
  k8s/pkg/condition/lke.go
  waitfor.go
Labels: changed

#169 Remove Limited from Object Storage Key Create Options
  object_storage_keys.go
  test/integration/fixtures/TestLimitedObjectStorageKeys.yaml
  test/integration/fixtures/TestLimitedObjectStorageKeys_bucket.yaml
  test/integration/fixtures/TestLimitedObjectStorageKeys_noaccess.yaml
  test/integration/object_storage_keys_test.go
Labels: removed
