Repository linode/linodego, pull requests merged in 2024-07, with the labels that each got.

#545 test: add submodule checkout in cross repo test workflow
  .github/workflows/release-cross-repo-test.yml
Labels: testing

#522 project: MultiCluster Object Storage
  client_test.go
  object_storage_bucket_certs.go
  object_storage_buckets.go
  object_storage_clusters.go
  object_storage_keys.go
  test/integration/fixtures/TestObjectStorageBucket_Regional.yaml
  test/integration/fixtures/TestObjectStorageKeys_Regional_Limited.yaml
  test/integration/object_storage_buckets_test.go
  test/integration/object_storage_keys_test.go
  test/integration/object_storage_object_test.go
Labels: new-feature

#548 Update api doc urls to point to new docs
  README.md
  instances.go
  profile_tokens.go
Labels: documentation

#556 Fix LKE node pool tests
  test/integration/fixtures/TestLKENodePoolNode_Delete.yaml
  test/integration/fixtures/TestLKENodePool_CreateWithLabelsAndTaints.yaml
  test/integration/fixtures/TestLKENodePool_GetFound.yaml
  test/integration/fixtures/TestLKENodePool_GetMissing.yaml
  test/integration/fixtures/TestLKENodePool_Update.yaml
  test/integration/fixtures/TestLKENodePools_List.yaml
  test/integration/lke_node_pools_test.go
Labels: testing

#554 Add project label
  .github/labels.yml
  .github/release.yml
Labels: repo-ci-improvement

#546 ref: PG affinity_type -> placement_group_type; is_strict -> placement_group_policy
  go.work.sum
  instances.go
  placement_groups.go
  test/integration/fixtures/TestInstance_withPG.yaml
  test/integration/fixtures/TestPlacementGroup_assignment.yaml
  test/integration/fixtures/TestPlacementGroup_basic.yaml
  test/integration/instances_test.go
  test/integration/main_test.go
  test/integration/placement_group_test.go
Labels: breaking-change, improvement

#558 fix: Separate plan availability logic from getRegionsWithCaps(...)
  test/integration/images_test.go
  test/integration/instance_config_test.go
  test/integration/instances_test.go
  test/integration/integration_suite_test.go
  test/integration/lke_clusters_test.go
  test/integration/lke_node_pools_test.go
  test/integration/mysql_test.go
  test/integration/nodebalancers_test.go
  test/integration/object_storage_buckets_test.go
  test/integration/object_storage_keys_test.go
  test/integration/placement_group_test.go
  test/integration/postgres_test.go
  test/integration/tags_test.go
  test/integration/vlans_test.go
  test/integration/volumes_test.go
  test/integration/vpc_subnet_test.go
  test/integration/vpc_test.go
  test/integration/waitfor_test.go
Labels: bugfix

#561 Integration test
  test/integration/account_invoice_test.go
  test/integration/account_settings_test.go
  test/integration/account_transfer_test.go
  test/integration/fixtures/TestAccountSettings.yaml
  test/integration/fixtures/TestAccountTransfer_Get.yaml
  test/integration/fixtures/TestIPv6Pool_Get.yaml
  test/integration/fixtures/TestIPv6Pool_List.yaml
  test/integration/fixtures/TestInvoiceItems_List.yaml
  test/integration/fixtures/TestInvoice_Get.yaml
  test/integration/fixtures/TestInvoice_List.yaml
  test/integration/fixtures/TestSecurityQuestions_List.yaml
  test/integration/fixtures/TestTicket_Get.yaml
  test/integration/fixtures/TestTicket_List.yaml
  test/integration/integration_suite_test.go
  test/integration/network_pools_test.go
  test/integration/profile_security_question_test.go
  test/integration/support_ticket_test.go
Labels: testing

#557 Implemented doRequest helper method
  client.go
  client_http.go
  client_test.go
  errors.go
  errors_test.go
Labels: improvement
