Repository linode/linodego, pull requests merged in 2024-03, with the labels that each got.

#464 fix: [BREAKING] Treat ip_ranges as a pointer in config interface update options
  instance_config_interfaces.go
  test/integration/fixtures/TestInstance_ConfigInterface_Update.yaml
  test/integration/instance_config_test.go
Labels: bugfix, breaking-change

#472 new: Bring EntityType and EntityAction enums to parity with API documentation
  account_events.go
Labels: added-feature

#461 feature: Add helper functions for working with errors
  errors.go
  errors_test.go
Labels: added-feature

#477 Add Updated and EOL Fields to Image
  images.go
  test/integration/fixtures/TestImage_GetFound.yaml
  test/integration/images_test.go
Labels: improvement

#479 fix: add missing labels
  .github/labels.yml
Labels: repo-ci-improvement

#481 Skip `TestBetaProgram_Get` When No Beta Program is Available
  test/integration/betas_test.go
  test/integration/fixtures/TestBetaProgram_Get.yaml
Labels: testing

#482 new: Add `SiteType` in regions
  regions.go
  test/integration/fixtures/TestRegions_List.yaml
Labels: new-feature
