Repository linode/linodego, pull requests merged in 2024-12, with the labels that each got.

#622 Added support for missing User-related fields
  account_user_grants.go
  account_users.go
  test/integration/account_user_grants_test.go
  test/integration/fixtures/TestInstance_GetMonthlyTransfer.yaml
  test/integration/fixtures/TestUserGrants_Update.yaml
  test/integration/fixtures/TestUserGrants_UpdateNoAccess.yaml
  test/unit/account_user_grants_test.go
  test/unit/account_users_test.go
  test/unit/fixtures/account_user_grants_get.json
  test/unit/fixtures/account_user_grants_update.json
  test/unit/fixtures/account_users_create.json
  test/unit/fixtures/account_users_get.json
  test/unit/fixtures/account_users_list.json
  test/unit/fixtures/account_users_update.json
Labels: improvement

#604 Add hardware type and linode label fields to volume struct
  test/integration/fixtures/TestVolume_WaitForLinodeID_linode.yaml
  test/integration/fixtures/TestVolume_WaitForLinodeID_nil.yaml
  test/integration/fixtures/TestVolume_WaitForLinodeID_volume.yaml
  test/integration/fixtures/TestVolume_WaitForLinodeID_waiting.yaml
  test/integration/volumes_test.go
  volumes.go
Labels: new-feature

#639 Fix: Updated PG migrations field to be pointer
  placement_groups.go
  test/integration/fixtures/TestInstance_Disk_Clone.yaml
  test/integration/fixtures/TestInstance_Disk_ResetPassword.yaml
  test/integration/fixtures/TestInstance_MigrateToPG.yaml
  test/integration/instances_test.go
Labels: bugfix, breaking-change

#632 Added support for missing Service Transfer related endpoints
  account_service_transfer.go
  test/unit/account_service_transfer_test.go
  test/unit/fixtures/account_service_transfers_get.json
  test/unit/fixtures/account_service_transfers_list.json
  test/unit/fixtures/account_service_transfers_request.json
Labels: improvement

#636 test: Add unit test coverage for account related functions; Add function and test coverage for reset oauth client secret endpoint
  account_oauth_client.go
  test/integration/account_oauth_client_test.go
  test/integration/fixtures/TestOAuthClients_Reset.yaml
  test/unit/account_availability_test.go
  test/unit/account_betas_test.go
  test/unit/account_logins_test.go
  test/unit/account_notifications_test.go
  test/unit/account_oauth_client_test.go
  test/unit/account_settings_test.go
  test/unit/fixtures/account_availability_get.json
  test/unit/fixtures/account_availability_list.json
  test/unit/fixtures/account_beta_get.json
  test/unit/fixtures/account_beta_list.json
  test/unit/fixtures/account_logins_get.json
  test/unit/fixtures/account_logins_list.json
  test/unit/fixtures/account_notifications_list.json
  test/unit/fixtures/account_oauth_client_create.json
  test/unit/fixtures/account_oauth_client_get.json
  test/unit/fixtures/account_oauth_client_list.json
  test/unit/fixtures/account_oauth_client_reset.json
  test/unit/fixtures/account_oauth_client_update.json
  test/unit/fixtures/account_settings_get.json
  test/unit/fixtures/account_settings_update.json
Labels: testing

#641 new: Introduce UpdateIPAddressV2; deprecate UpdateIPAddress
  network_ips.go
  test/integration/account_oauth_client_test.go
  test/integration/domains_test.go
  test/integration/fixtures/TestIPAddress_GetFound.yaml
  test/integration/fixtures/TestIPAddress_GetMissing.yaml
  test/integration/fixtures/TestIPAddress_Instance_Allocate.yaml
  test/integration/fixtures/TestIPAddress_Instance_Assign.yaml
  test/integration/fixtures/TestIPAddress_Instance_Delete.yaml
  test/integration/fixtures/TestIPAddress_Instance_ReserveIP_Assign.yaml
  test/integration/fixtures/TestIPAddress_Instance_Share.yaml
  test/integration/fixtures/TestIPAddress_Update.yaml
  test/integration/fixtures/TestIPAddresses_Instance_Get.yaml
  test/integration/fixtures/TestIPAddresses_List.yaml
  test/integration/instances_test.go
  test/integration/network_ips_test.go
  test/integration/network_reserved_ips_test.go
  test/unit/account_agreements_test.go
  test/unit/account_availability_test.go
  test/unit/account_betas_test.go
  test/unit/account_events_test.go
  test/unit/account_invoices_test.go
  test/unit/account_logins_test.go
  test/unit/account_notifications_test.go
  test/unit/account_oauth_client_test.go
  test/unit/account_payment_methods_test.go
  test/unit/account_payments_test.go
  test/unit/account_promo_credits_test.go
  test/unit/account_service_transfer_test.go
  test/unit/account_settings_test.go
  test/unit/account_test.go
  test/unit/account_user_grants_test.go
  test/unit/account_users_test.go
  test/unit/domain_test.go
  test/unit/instance_disks_test.go
  test/unit/instance_nodebalancers_test.go
  test/unit/instance_test.go
  test/unit/object_storage_test.go
  test/unit/placement_group_test.go
  test/unit/profile_apps_test.go
  test/unit/profile_devices_test.go
  test/unit/profile_preferences_test.go
  test/unit/profile_test.go
  test/unit/support_test.go
Labels: new-feature
