Repository linode/linodego, pull requests merged in 2024-11, with the labels that each got.

#598 Added support for missing Account-related endpoints
  account.go
  account_agreements.go
  account_maintenance.go
  go.work.sum
  test/integration/account_agreements_test.go
  test/integration/account_maintenance_test.go
  test/integration/fixtures/TestAccountAgreements_List.yaml
  test/integration/fixtures/TestAccountMaintenances_List.yaml
  test/unit/account_agreements_test.go
  test/unit/account_maintenance_test.go
  test/unit/account_test.go
  test/unit/fixtures/account_agreements_get.json
  test/unit/fixtures/account_maintenance_list.json
  test/unit/fixtures/account_update.json
Labels: improvement

#601 Added support for missing Payment-related endpoints
  account_payment_methods.go
  account_payments.go
  account_promo_credits.go
  test/unit/account_payment_methods_test.go
  test/unit/account_payments_test.go
  test/unit/account_promo_credits_test.go
  test/unit/fixtures/account_payment_create.json
  test/unit/fixtures/account_payment_methods_get.json
  test/unit/fixtures/account_payment_methods_list.json
  test/unit/fixtures/account_promo_credits_add_promo_code.json
Labels: improvement

#603 Fix lint issues and organize linters
  .golangci.yml
  client.go
  config.go
  waitfor.go
Labels: improvement

#595 Updated log formatting to more closely resemble Resty's
  client.go
  client_test.go
  request_log_template.tmpl
  response_log_template.tmpl
Labels: improvement

#612 Added support for missing Account-related fields
  account.go
  account_events.go
  account_invoices.go
  profile.go
  support.go
  test/integration/account_invoice_test.go
  test/integration/fixtures/TestAccountEvents_List.yaml
  test/integration/fixtures/TestAccount_Get.yaml
  test/integration/fixtures/TestInvoiceItems_List.yaml
  test/integration/fixtures/TestInvoice_Get.yaml
  test/integration/fixtures/TestInvoice_List.yaml
  test/integration/fixtures/TestProfile_Get.yaml
  test/integration/fixtures/TestProfile_Update.yaml
  test/integration/fixtures/TestTicket_Get.yaml
  test/integration/fixtures/TestTicket_List.yaml
  test/integration/support_ticket_test.go
  test/unit/account_events_test.go
  test/unit/account_invoices_test.go
  test/unit/account_test.go
  test/unit/fixtures/account_events_get.json
  test/unit/fixtures/account_events_list.json
  test/unit/fixtures/account_get.json
  test/unit/fixtures/account_invoice_items_list.json
  test/unit/fixtures/account_invoices_get.json
  test/unit/fixtures/account_invoices_list.json
  test/unit/fixtures/profile_get.json
  test/unit/fixtures/profile_update.json
  test/unit/fixtures/support_ticket_get.json
  test/unit/fixtures/support_ticket_list.json
  test/unit/profile_test.go
  test/unit/support_test.go
Labels: bugfix, improvement

#616 Added support for missing Profile-related endpoints
  profile_apps.go
  profile_devices.go
  profile_preferences.go
  test/unit/fixtures/profile_apps_get.json
  test/unit/fixtures/profile_apps_list.json
  test/unit/fixtures/profile_devices_get.json
  test/unit/fixtures/profile_devices_list.json
  test/unit/fixtures/profile_preferences_get.json
  test/unit/fixtures/profile_preferences_update.json
  test/unit/profile_apps_test.go
  test/unit/profile_devices_test.go
  test/unit/profile_preferences_test.go
Labels: improvement

#617 Added support for `migrations` field for Placement Groups
  placement_groups.go
  test/integration/fixtures/TestInstance_MigrateToPG.yaml
  test/integration/instances_test.go
  test/unit/fixtures/placement_group_assign.json
  test/unit/fixtures/placement_group_create.json
  test/unit/fixtures/placement_group_unassign.json
  test/unit/fixtures/placement_group_update.json
  test/unit/fixtures/placement_groups_get.json
  test/unit/fixtures/placement_groups_list.json
  test/unit/placement_group_test.go
Labels: improvement

#618 Support missing fields in Instance and LKE ACL
  instances.go
  lke_clusters_control_plane.go
  test/integration/fixtures/TestInstance_Get.yaml
  test/integration/fixtures/TestLKECluster_withACL.yaml
  test/integration/lke_clusters_acl_test.go
  test/unit/fixtures/linodes_list.json
  test/unit/instance_test.go
Labels: improvement

#620 Support missing domain-related endpoints for API parity
  domains.go
  test/integration/domains_test.go
  test/integration/fixtures/TestDomain_Clone.yaml
  test/unit/domain_test.go
  test/unit/fixtures/domain_clone.json
  test/unit/fixtures/domain_import.json
  test/unit/util_test.go
Labels: improvement

#623 test: Update default test image to reflect the deprecation of Debian 9 support
  test/integration/instances_test.go
Labels: testing

#628 doc: Remove Image Services Gen2 LA notice
  images.go
Labels: documentation
