Repository linode/linodego, pull requests merged in 2024-04, with the labels that each got.

#490 new: Add support for VM Placement
  instances.go
  placement_groups.go
  regions.go
  test/go.mod
  test/integration/fixtures/TestInstance_withPG.yaml
  test/integration/fixtures/TestPlacementGroup_assignment.yaml
  test/integration/fixtures/TestPlacementGroup_basic.yaml
  test/integration/fixtures/TestRegions_pgLimits.yaml
  test/integration/instances_test.go
  test/integration/placement_group_test.go
  test/integration/regions_test.go
Labels: improvement, new-feature

#491 new: Support `available` for AccountAvailability
  account_availability.go
  go.work.sum
  test/integration/fixtures/TestAccountAvailability_Get.yaml
  test/integration/fixtures/TestAccountAvailability_List.yaml
Labels: new-feature

#492 new: Add event entities enums and actions VM Placement
  account_events.go
  go.work.sum
Labels: new-feature

#494 Dependencies update for k8s and test sub-packages
  go.work.sum
  k8s/go.mod
  k8s/go.sum
  test/go.mod
  test/go.sum
Labels: dependencies
