Repository linode/linodego, pull requests merged in 2024-05, with the labels that each got.

#493 CI Cleanup
  .github/workflows/ci.yml
  .github/workflows/pull_request.yml
  .github/workflows/release-cross-repo-test.yml
  README.md
  test/unit/util_test.go
Labels: repo-ci-improvement

#496 ref: Fix case in name for `Client.UnassignPlacementGroupLinodes(...)`
  placement_groups.go
  test/integration/placement_group_test.go
Labels: improvement

#495 new: [BREAKING] Add support for LKE Control Plane ACL
  account_events.go
  go.work.sum
  lke_clusters.go
  lke_clusters_control_plane.go
  test/go.mod
  test/integration/fixtures/TestLKECluster_withACL.yaml
  test/integration/lke_clusters_acl_test.go
  test/integration/lke_clusters_test.go
Labels: breaking-change, new-feature

#502 CI: replace test execution handler with conditional
  .github/workflows/ci.yml
Labels: repo-ci-improvement

#501 Mask the value of the Authorization header if debug is enabled
  client.go
  client_test.go
  internal/testutil/mock.go
Labels: improvement

#507 Expose region capabilities enum
  regions.go
Labels: improvement

#508 fix: Prevent unexpected warning from Resty when calling `Client.SetDebug(false)`
  client.go
Labels: bugfix
