Repository linode/linodego, pull requests merged in 2024-10, with the labels that each got.

#588 ci: Fix workflow failures in PRs due to slack notify step
  .github/workflows/ci.yml
Labels: repo-ci-improvement

#572 Added support for Block Storage Encryption
  instances.go
  regions.go
  test/integration/fixtures/TestInstance_withBlockStorageEncryption.yaml
  test/integration/fixtures/TestRegions_blockStorageEncryption.yaml
  test/integration/fixtures/TestVolume_Create_withEncryption.yaml
  test/integration/fixtures/TestVolume_Get_withEncryption.yaml
  test/integration/instances_test.go
  test/integration/regions_test.go
  test/integration/volumes_test.go
  volumes.go
Labels: new-feature

#590 Remove Placement Group LA notices
  go.work.sum
  instances.go
  placement_groups.go
Labels: documentation

#576 Drop Resty as a dependency
  .github/workflows/ci.yml
  client.go
  client_http.go
  client_test.go
  config_test.go
  errors.go
  errors_test.go
  go.mod
  go.sum
  go.work.sum
  images.go
  internal/testutil/mock.go
  k8s/go.mod
  k8s/go.sum
  logger.go
  pagination.go
  request_helpers.go
  request_helpers_test.go
  retries.go
  retries_http.go
  retries_http_test.go
  retries_test.go
  test/go.mod
  test/go.sum
  test/integration/cache_test.go
  test/unit/client_test.go
Labels: improvement

#592 Add missing 'upgrade' field to DC migration endpoint
  instances.go
  test/integration/fixtures/TestInstance_Migrate.yaml
  test/integration/instances_test.go
  test/unit/instance_test.go
Labels: improvement

#593 Disallow configuring a custom root CA with a custom RoundTripper
  client.go
  client_test.go
Labels: improvement

#599 CI: Notify slack channel on releases
  .github/workflows/release-notify-slack.yml
Labels: repo-ci-improvement
