Repository linode/linodego, pull requests merged in 2024-09, with the labels that each got.

#571 Implemented new middleware system
  client.go
  client_http.go
  client_test.go
Labels: improvement

#573 new: Add support LKE, Volume, NodeBalancer, and network transfer pricing endpoints
  base_types.go
  lke_types.go
  network_transfer_prices.go
  nodebalancer_types.go
  test/integration/fixtures/TestLKEType_List.yaml
  test/integration/fixtures/TestNetworkTransferPrice_List.yaml
  test/integration/fixtures/TestNodeBalancerType_List.yaml
  test/integration/fixtures/TestVolumeType_List.yaml
  test/integration/lke_types_test.go
  test/integration/network_transfer_prices_test.go
  test/integration/nodebalancer_types_test.go
  test/integration/volume_types_test.go
  volumes_types.go
Labels: new-feature

#582 Improve image replication test region; Add LA notice
  images.go
  test/integration/fixtures/TestImage_Replicate.yaml
  test/integration/images_test.go
  test/integration/integration_suite_test.go
Labels: testing

#585 test: Add slack notifications to CI workflow
  .github/workflows/ci.yml
Labels: testing
