Repository linode/linodego, pull requests merged in 2025-04, with the labels that each got.

#700 Added missing options for POST and PUT methods
  account_child.go
  account_invoices.go
  account_logins.go
  account_notifications.go
  account_oauth_client.go
  instance_disks.go
  instance_ips.go
  instance_snapshots.go
  instances.go
  request_helpers.go
  test/integration/example_nodebalancers_test.go
  test/integration/instance_snapshots_test.go
  test/integration/instances_test.go
  test/integration/network_ips_test.go
  test/integration/nodebalancer_config_nodes_test.go
  test/integration/volumes_test.go
  test/integration/waitfor_test.go
  test/unit/instance_disks_test.go
  test/unit/volume_test.go
  volumes.go
Labels: improvement

#701 Support new fields for LKE-E node pool
  lke_node_pools.go
  test/integration/fixtures/TestLKENodeEnterprisePoolNode_Get.yaml
  test/integration/fixtures/TestLKENodeEnterprisePoolNode_Update.yaml
  test/integration/lke_node_pools_test.go
  test/unit/fixtures/lke_e_node_pool_create.json
  test/unit/fixtures/lke_e_node_pool_update.json
  test/unit/lke_node_pools_test.go
Labels: new-feature

#712 Add option to disable cloud firewall when running integration tests
  test/integration/fixtures/TestInstanceBackups_List.yaml
  test/integration/instance_snapshots_test.go
  test/integration/main_test.go
Labels: testing

#706 Implement support for VPC Dual Stack
  client.go
  helpers_iterator.go
  instance_config_interfaces.go
  instance_configs.go
  instance_ips.go
  test/unit/fixtures/instance_config_create.json
  test/unit/fixtures/instance_config_get.json
  test/unit/fixtures/instance_config_interface_create.json
  test/unit/fixtures/instance_config_interface_get.json
  test/unit/fixtures/instance_config_interface_list.json
  test/unit/fixtures/instance_config_interface_update.json
  test/unit/fixtures/instance_config_list.json
  test/unit/fixtures/instance_config_update.json
  test/unit/fixtures/vpc_get.json
  test/unit/fixtures/vpc_ips_list.json
  test/unit/fixtures/vpc_list.json
  test/unit/fixtures/vpc_specific_ips_list.json
  test/unit/fixtures/vpc_subnet_create.json
  test/unit/fixtures/vpc_subnet_get.json
  test/unit/fixtures/vpc_subnet_update.json
  test/unit/fixtures/vpc_subnets_list.json
  test/unit/instance_config_interfaces_test.go
  test/unit/instance_config_test.go
  test/unit/util.go
  test/unit/vpc_ips_test.go
  test/unit/vpc_subnets_test.go
  test/unit/vpc_test.go
  vpc.go
  vpc_subnet.go
Labels: new-feature

#718 Update LDE capability name and tests
  regions.go
  test/integration/fixtures/TestLKECluster_APIEndpoints_List.yaml
  test/integration/fixtures/TestLKECluster_APLEnabled.yaml
  test/integration/fixtures/TestLKECluster_Dashboard_Get.yaml
  test/integration/fixtures/TestLKECluster_Enterprise_smoke.yaml
  test/integration/fixtures/TestLKECluster_GetFound.yaml
  test/integration/fixtures/TestLKECluster_GetMissing.yaml
  test/integration/fixtures/TestLKECluster_Kubeconfig_Delete.yaml
  test/integration/fixtures/TestLKECluster_Kubeconfig_Get.yaml
  test/integration/fixtures/TestLKECluster_Nodes_Recycle.yaml
  test/integration/fixtures/TestLKECluster_Update.yaml
  test/integration/fixtures/TestLKECluster_WaitForReady.yaml
  test/integration/fixtures/TestLKECluster_WaitForReady_Cluster.yaml
  test/integration/fixtures/TestLKECluster_withACL.yaml
  test/integration/fixtures/TestLKEClusters_List.yaml
  test/integration/fixtures/TestLKENodeEnterprisePoolNode_Get.yaml
  test/integration/fixtures/TestLKENodeEnterprisePoolNode_Update.yaml
  test/integration/fixtures/TestLKENodePoolNode_Delete.yaml
  test/integration/fixtures/TestLKENodePoolNode_Get.yaml
  test/integration/fixtures/TestLKENodePoolNode_Recycle.yaml
  test/integration/fixtures/TestLKENodePool_CreateWithLabelsAndTaints.yaml
  test/integration/fixtures/TestLKENodePool_GetFound.yaml
  test/integration/fixtures/TestLKENodePool_GetFound_k8s.yaml
  test/integration/fixtures/TestLKENodePool_GetMissing.yaml
  test/integration/fixtures/TestLKENodePool_Recycle.yaml
  test/integration/fixtures/TestLKENodePool_Update.yaml
  test/integration/fixtures/TestLKENodePools_List.yaml
  test/integration/lke_clusters_test.go
  test/integration/lke_node_pools_test.go
Labels: testing

#715 Implement changes for account APIs
  account_settings.go
  test/integration/account_settings_test.go
  test/integration/fixtures/TestAccountSettings.yaml
  test/unit/account_settings_test.go
  test/unit/fixtures/account_settings_get.json
  test/unit/fixtures/account_settings_update.json
Labels: new-feature

#727 Added support for `networking/` and `vpcs/` endpoint changs for VPC Linodes Enhanced Interfaces
  firewall_devices.go
  firewalls.go
  go.work.sum
  instance_ips.go
  regions.go
  test/unit/firewalls_test.go
  test/unit/fixtures/default_firewalls_get.json
  test/unit/fixtures/default_firewalls_update.json
  test/unit/fixtures/network_ip_address_get.json
  test/unit/fixtures/network_ip_addresses_list.json
  test/unit/fixtures/vpc_get.json
  test/unit/fixtures/vpc_list.json
  test/unit/fixtures/vpc_subnet_get.json
  test/unit/fixtures/vpc_subnets_list.json
  test/unit/network_ips_test.go
  test/unit/vpc_subnets_test.go
  test/unit/vpc_test.go
  vpc_subnet.go
Labels: new-feature

#729 Removed invalid fields from Configurable DB changes
  mysql.go
  postgres.go
  test/unit/fixtures/mysql_database_config_get.json
  test/unit/fixtures/mysql_database_create.json
  test/unit/fixtures/mysql_database_get.json
  test/unit/fixtures/mysql_database_update.json
  test/unit/fixtures/postgresql_database_config_get.json
  test/unit/fixtures/postgresql_database_create.json
  test/unit/fixtures/postgresql_database_get.json
  test/unit/fixtures/postgresql_database_update.json
  test/unit/mysql_test.go
  test/unit/postgres_test.go
Labels: new-feature

#728 Add integration tests for Configurable DB Params
  Makefile
  test/integration/fixtures/TestDatabaseMySQLConfig_Get.yaml
  test/integration/fixtures/TestDatabaseMySQL_EngineConfig_Suite.yaml
  test/integration/fixtures/TestDatabasePostgresConfig_Get.yaml
  test/integration/fixtures/TestDatabasePostgres_EngineConfig_Suite.yaml
  test/integration/mysql_db_config_test.go
  test/integration/postgres_db_config_test.go
Labels: testing

#722 Adding ACLP monitor APIs
  monitor_dashboards.go
  monitor_metrics_definitions.go
  monitor_services.go
  monitor_services_create_token.go
  test/integration/fixtures/TestDatabaseACLP_List.yaml
  test/integration/fixtures/TestMonitorDashboards_Get.yaml
  test/integration/fixtures/TestMonitorMetricDefinitions_Get.yaml
  test/integration/fixtures/TestMonitorServices_Get.yaml
  test/integration/fixtures/TestServiceToken_POST.yaml
  test/integration/monitor_dashboards_test.go
  test/integration/monitor_metrics_definitions_test.go
  test/integration/monitor_services_test.go
  test/integration/monitor_services_token_creation_test.go
  test/unit/fixtures/monitor_dashboard_by_id.json
  test/unit/fixtures/monitor_dashboard_by_service_type.json
  test/unit/fixtures/monitor_dashboards.json
  test/unit/fixtures/monitor_service_metrics.json
  test/unit/fixtures/monitor_service_token_create.json
  test/unit/fixtures/monitor_services.json
  test/unit/monitor_dashboards_test.go
  test/unit/monitor_services_metrics_definition_test.go
  test/unit/monitor_services_test.go
  test/unit/monitor_services_token_test.go
Labels: new-feature

#725 Skip monthly transfer v1 test on 32 bits systems
  test/unit/instance_test.go
Labels: testing
