Repository linode/linodego, pull requests merged in 2025-01, with the labels that each got.

#633 Support DBaaS V2.0
  databases.go
  go.work.sum
  mysql.go
  postgres.go
  test/integration/databases_test.go
  test/integration/fixtures/TestDatabase_Engine.yaml
  test/integration/fixtures/TestDatabase_List.yaml
  test/integration/fixtures/TestDatabase_MySQL_Suite.yaml
  test/integration/fixtures/TestDatabase_Postgres_Suite.yaml
  test/integration/fixtures/TestDatabase_Type.yaml
  test/integration/mysql_test.go
  test/integration/postgres_test.go
  waitfor.go
Labels: improvement

#643 Remove unnecessary permissions for codeql scan workflow
  .github/workflows/codeql.yml
Labels: ignore-for-release

#647 Add unit test coverage for Type, Vlan and Tag related methods/functions
  go.work
  go.work.sum
  k8s/go.mod
  k8s/go.sum
  test/go.mod
  test/go.sum
  test/unit/fixtures/linode_type_get.json
  test/unit/fixtures/linode_types_list.json
  test/unit/fixtures/tag_create.json
  test/unit/fixtures/tagged_objects_list.json
  test/unit/fixtures/tags_list.json
  test/unit/fixtures/vlan_get_ipam_address.json
  test/unit/fixtures/vlans_list.json
  test/unit/tag_test.go
  test/unit/types_test.go
  test/unit/vlan_test.go
Labels: testing

#645 VPU Support
  instances.go
  regions.go
  test/integration/fixtures/TestInstance_withVPU.yaml
  test/integration/instances_test.go
  types.go
Labels: improvement

#652 Add unit test coverage for Stackscripts, Database and Region related methods/functions
  test/unit/.DS_Store
  test/unit/database_test.go
  test/unit/fixtures/database_engine_get.json
  test/unit/fixtures/database_maintenance_window.json
  test/unit/fixtures/database_types_list.json
  test/unit/fixtures/database_unmarshal.json
  test/unit/fixtures/databases_list.json
  test/unit/fixtures/region_availability_get.json
  test/unit/fixtures/region_get.json
  test/unit/fixtures/regions_availability_list.json
  test/unit/fixtures/regions_list.json
  test/unit/fixtures/stackscript_get.json
  test/unit/fixtures/stackscript_revision.json
  test/unit/fixtures/stackscripts_list.json
  test/unit/region_test.go
  test/unit/stackscripts_test.go
Labels: testing

#657 test/workflow: Update make test commands and related workflows
  .github/workflows/ci.yml
  .github/workflows/nightly_smoke_tests.yml
  .github/workflows/release-cross-repo-test.yml
  Makefile
  README.md
  test/Makefile
Labels: repo-ci-improvement, testing

#659 Added missing db-related fields
  databases.go
  go.work.sum
  mysql.go
  postgres.go
  test/integration/fixtures/TestDatabase_Engine.yaml
  test/integration/fixtures/TestDatabase_List.yaml
  test/integration/fixtures/TestDatabase_MySQL_Suite.yaml
  test/integration/fixtures/TestDatabase_Postgres_Suite.yaml
  test/integration/fixtures/TestDatabase_Type.yaml
  test/unit/fixtures/mysql_database_create.json
  test/unit/fixtures/mysql_database_credentials_get.json
  test/unit/fixtures/mysql_database_get.json
  test/unit/fixtures/mysql_database_ssl_get.json
  test/unit/fixtures/mysql_database_update.json
  test/unit/fixtures/mysql_databases_list.json
  test/unit/fixtures/postgresql_database_create.json
  test/unit/fixtures/postgresql_database_credentials_get.json
  test/unit/fixtures/postgresql_database_get.json
  test/unit/fixtures/postgresql_database_ssl_get.json
  test/unit/fixtures/postgresql_database_update.json
  test/unit/fixtures/postgresql_databases_list.json
  test/unit/mysql_test.go
  test/unit/postgres_test.go
Labels: improvement

#664 test: remove extra test param in Makefile
  Makefile
Labels: testing
