Repository linode/linodego, pull requests merged in 2025-03, with the labels that each got.

#690 Add unit test coverage for Instance related methods/functions
  test/unit/fixtures/instance_backups_get.json
  test/unit/fixtures/instance_clone.json
  test/unit/fixtures/instance_config_create.json
  test/unit/fixtures/instance_config_get.json
  test/unit/fixtures/instance_config_interface_create.json
  test/unit/fixtures/instance_config_interface_get.json
  test/unit/fixtures/instance_config_interface_list.json
  test/unit/fixtures/instance_config_interface_update.json
  test/unit/fixtures/instance_config_list.json
  test/unit/fixtures/instance_config_update.json
  test/unit/fixtures/instance_create.json
  test/unit/fixtures/instance_disk_create.json
  test/unit/fixtures/instance_disk_get.json
  test/unit/fixtures/instance_disk_list.json
  test/unit/fixtures/instance_disk_update.json
  test/unit/fixtures/instance_firewall_list.json
  test/unit/fixtures/instance_get.json
  test/unit/fixtures/instance_ip_add.json
  test/unit/fixtures/instance_ip_get.json
  test/unit/fixtures/instance_ip_list.json
  test/unit/fixtures/instance_ip_reserved.json
  test/unit/fixtures/instance_ip_update.json
  test/unit/fixtures/instance_rebuild.json
  test/unit/fixtures/instance_snapshot_create.json
  test/unit/fixtures/instance_snapshot_get.json
  test/unit/fixtures/instance_update.json
  test/unit/fixtures/instance_volume_list.json
  test/unit/instance_backup_test.go
  test/unit/instance_config_interfaces_test.go
  test/unit/instance_config_test.go
  test/unit/instance_disks_test.go
  test/unit/instance_firewall_test.go
  test/unit/instance_ip_test.go
  test/unit/instance_test.go
  test/unit/instance_volume_test.go
Labels: testing

#691 Fix LKE tier version URLs
  lke_clusters.go
  test/integration/fixtures/TestLKETierVersion_ListAndGet.yaml
Labels: bugfix

#696 Remove support for deprecated fields and endpoints
  account_events.go
  account_settings.go
  databases.go
  domains.go
  instance_ips.go
  instances.go
  lke_cluster_pools.go
  mysql.go
  network_ips.go
  object_storage_bucket_certs.go
  object_storage_buckets.go
  object_storage_clusters.go
  object_storage_keys.go
  object_storage_object.go
  paged_response_structs.go
  pagination.go
  postgres.go
  regions.go
  test/integration/account_settings_test.go
  test/integration/fixtures/TestAccountEvents_List.yaml
  test/integration/fixtures/TestObjectStorageBucketCert.yaml
  test/integration/fixtures/TestObjectStorageBucket_Access_Get.yaml
  test/integration/fixtures/TestObjectStorageBucket_Access_Update.yaml
  test/integration/fixtures/TestObjectStorageBucket_Create.yaml
  test/integration/fixtures/TestObjectStorageBucket_GetFound.yaml
  test/integration/fixtures/TestObjectStorageBucket_GetMissing.yaml
  test/integration/fixtures/TestObjectStorageBucket_Regional.yaml
  test/integration/fixtures/TestObjectStorageBucketsInCluster_List.yaml
  test/integration/fixtures/TestObjectStorageBuckets_List.yaml
  test/integration/fixtures/TestObjectStorageClusters_List.yaml
  test/integration/fixtures/TestObjectStorageKey_GetFound.yaml
  test/integration/fixtures/TestObjectStorageKey_GetMissing.yaml
  test/integration/fixtures/TestObjectStorageKey_List.yaml
  test/integration/fixtures/TestObjectStorageKey_Update.yaml
  test/integration/fixtures/TestObjectStorageKeys_Limited.yaml
  test/integration/fixtures/TestObjectStorageKeys_Limited_Bucket.yaml
  test/integration/fixtures/TestObjectStorageKeys_Regional_Limited.yaml
  test/integration/fixtures/TestObjectStorageObject_ACLConfig_Bucket_Delete.yaml
  test/integration/fixtures/TestObjectStorageObject_ACLConfig_Bucket_Put.yaml
  test/integration/fixtures/TestObjectStorageObject_Smoke.yaml
  test/integration/object_storage_bucket_certs_test.go
  test/integration/object_storage_buckets_test.go
  test/integration/object_storage_clusters_test.go
  test/integration/object_storage_keys_test.go
  test/integration/object_storage_object_test.go
  waitfor.go
Labels: breaking-change
