Repository linode/linodego, pull requests merged in 2025-05, with the labels that each got.

#732 Add obj storage quotas integration tests
  test/integration/fixtures/TestObjectStorageQuotaUsage_Get.yaml
  test/integration/fixtures/TestObjectStorageQuotas_Get.yaml
  test/integration/fixtures/TestObjectStorageQuotas_List.yaml
  test/integration/object_storage_quota_test.go
Labels: testing

#739 Update monthly transfer test fixture
  test/integration/fixtures/TestInstance_GetMonthlyTransfer.yaml
Labels: testing

#738 Project: Limits Visibility M1
  object_storage_quota.go
  test/integration/fixtures/TestObjectStorageQuotaUsage_Get.yaml
  test/integration/fixtures/TestObjectStorageQuotas_Get.yaml
  test/integration/fixtures/TestObjectStorageQuotas_List.yaml
  test/integration/object_storage_quota_test.go
  test/unit/fixtures/object_storage_quotas_get.json
  test/unit/fixtures/object_storage_quotas_list.json
  test/unit/fixtures/object_storage_quotas_usage_get.json
  test/unit/object_storage_quota_test.go
Labels: project

#720 Added support for Host/VM Maintenance
  account_events.go
  account_maintenance.go
  account_notifications.go
  account_settings.go
  go.work.sum
  instances.go
  maintenance_policy.go
  regions.go
  test/unit/account_events_test.go
  test/unit/account_maintenance_test.go
  test/unit/account_settings_test.go
  test/unit/fixtures/account_events_get.json
  test/unit/fixtures/account_events_list.json
  test/unit/fixtures/account_maintenance_list.json
  test/unit/fixtures/account_settings_get.json
  test/unit/fixtures/account_settings_update.json
  test/unit/fixtures/instance_clone.json
  test/unit/fixtures/instance_create.json
  test/unit/fixtures/instance_get.json
  test/unit/fixtures/instance_update.json
  test/unit/fixtures/linodes_list.json
  test/unit/fixtures/maintenance_policies_list.json
  test/unit/instance_test.go
  test/unit/maintenance_policy_test.go
Labels: new-feature

#742 Allow nullable DB Engine Config fields to be set to explicit null values
  mysql.go
  test/integration/fixtures/TestDatabaseMySQL_EngineConfig_Create_NullableFieldAsNilValue.yaml
  test/integration/fixtures/TestDatabaseMySQL_EngineConfig_Get.yaml
  test/integration/fixtures/TestDatabaseMySQL_EngineConfig_Suite.yaml
  test/integration/fixtures/TestDatabasePostgres_EngineConfig_Create_PasswordEncryption_DefaultsToMD5.yaml
  test/integration/fixtures/TestDatabasePostgres_EngineConfig_Get.yaml
  test/integration/fixtures/TestDatabasePostgres_EngineConfig_Suite.yaml
  test/integration/mysql_db_config_test.go
  test/integration/postgres_db_config_test.go
  test/unit/mysql_test.go
Labels: bugfix

#748 Add lke versions helper and update tests
  Makefile
  test/Makefile
  test/integration/fixtures/TestLKECluster_APIEndpoints_List.yaml
  test/integration/fixtures/TestLKECluster_APLEnabled.yaml
  test/integration/fixtures/TestLKECluster_Dashboard_Get.yaml
  test/integration/fixtures/TestLKECluster_Enterprise_smoke.yaml
  test/integration/fixtures/TestLKECluster_GetFound.yaml
  test/integration/fixtures/TestLKECluster_GetMissing.yaml
  test/integration/fixtures/TestLKECluster_Kubeconfig_Delete.yaml
  test/integration/fixtures/TestLKECluster_Kubeconfig_Get.yaml
  test/integration/fixtures/TestLKECluster_Nodes_Recycle.yaml
  test/integration/fixtures/TestLKECluster_Update.yaml
  test/integration/fixtures/TestLKECluster_WaitForReady.yaml
  test/integration/fixtures/TestLKECluster_WaitForReady_Cluster.yaml
  test/integration/fixtures/TestLKECluster_withACL.yaml
  test/integration/fixtures/TestLKEClusters_List.yaml
  test/integration/fixtures/TestLKENodePoolNode_Delete.yaml
  test/integration/fixtures/TestLKENodePoolNode_Get.yaml
  test/integration/fixtures/TestLKENodePoolNode_Recycle.yaml
  test/integration/fixtures/TestLKENodePool_CreateWithLabelsAndTaints.yaml
  test/integration/fixtures/TestLKENodePool_GetFound.yaml
  test/integration/fixtures/TestLKENodePool_GetFound_k8s.yaml
  test/integration/fixtures/TestLKENodePool_GetMissing.yaml
  test/integration/fixtures/TestLKENodePool_Recycle.yaml
  test/integration/fixtures/TestLKENodePool_Update.yaml
  test/integration/fixtures/TestLKENodePools_List.yaml
  test/integration/fixtures/TestLKETierVersion_ListAndGet.yaml
  test/integration/lke_clusters_test.go
Labels: testing

#724 Adding VPC Enhanced Interfaces
  interfaces.go
  test/unit/fixtures/interface_create.json
  test/unit/fixtures/interface_get.json
  test/unit/fixtures/interface_list.json
  test/unit/fixtures/interface_settings_get.json
  test/unit/fixtures/interface_settings_update.json
  test/unit/fixtures/interface_update.json
  test/unit/fixtures/interface_upgrade.json
  test/unit/interface_test.go
Labels: new-feature

#750 Updated type for modified fields
  postgres.go
  test/integration/fixtures/TestDatabasePostgres_EngineConfig_Get.yaml
  test/integration/postgres_db_config_test.go
  test/unit/fixtures/postgresql_database_config_get.json
  test/unit/postgres_test.go
Labels: bugfix

#749 Fix tag for LKE control plane ACL revision ID field
  lke_clusters_control_plane.go
  test/integration/fixtures/TestLKECluster_withACL.yaml
  test/integration/lke_clusters_acl_test.go
  test/unit/fixtures/lke_cluster_control_plane_acl_get.json
  test/unit/fixtures/lke_cluster_control_plane_acl_update.json
Labels: bugfix

#736 fix: update MigratingTo field to accept int or null
  instances.go
  test/integration/fixtures/TestInstance_Get.yaml
  test/integration/fixtures/TestInstance_MigrateToPG.yaml
  test/integration/fixtures/TestInstances_List.yaml
  test/integration/instances_test.go
  test/unit/fixtures/instance_get.json
  test/unit/fixtures/linodes_list.json
  test/unit/instance_test.go
Labels: bugfix, breaking-change

#752 Drop v4beta and LA notice for Limits Visibility
  object_storage_quota.go
Labels: documentation

#746 ACLP: updating variable type for entity_ids for different service_types
  monitor_services_create_token.go
  test/integration/fixtures/TestDatabaseACLP_List.yaml
  test/integration/fixtures/TestServiceToken_POST.yaml
  test/integration/monitor_services_token_creation_test.go
  test/unit/monitor_services_token_test.go
Labels: improvement

#723 Linode instance and interfaces changes
  go.work.sum
  instances.go
  interfaces.go
  test/integration/fixtures/TestInstance_CreateWithLinodeInterfaces.yaml
  test/integration/instance_interfaces_test.go
  test/integration/vpc_subnet_test.go
Labels: new-feature

#755 Project: Configurable DB Params
  Makefile
  mysql.go
  postgres.go
  test/integration/fixtures/TestDatabaseMySQL_EngineConfig_Create_NullableFieldAsNilValue.yaml
  test/integration/fixtures/TestDatabaseMySQL_EngineConfig_Get.yaml
  test/integration/fixtures/TestDatabaseMySQL_EngineConfig_Suite.yaml
  test/integration/fixtures/TestDatabasePostgres_EngineConfig_Create_PasswordEncryption_DefaultsToMD5.yaml
  test/integration/fixtures/TestDatabasePostgres_EngineConfig_Get.yaml
  test/integration/fixtures/TestDatabasePostgres_EngineConfig_Suite.yaml
  test/integration/mysql_db_config_test.go
  test/integration/postgres_db_config_test.go
  test/unit/fixtures/mysql_database_config_get.json
  test/unit/fixtures/mysql_database_create.json
  test/unit/fixtures/mysql_database_get.json
  test/unit/fixtures/mysql_database_update.json
  test/unit/fixtures/postgresql_database_config_get.json
  test/unit/fixtures/postgresql_database_create.json
  test/unit/fixtures/postgresql_database_get.json
  test/unit/fixtures/postgresql_database_update.json
  test/unit/mysql_test.go
  test/unit/postgres_test.go
Labels: project
