Repository linode/linodego, pull requests merged in 2025-02, with the labels that each got.

#661 Add unit test coverage for Volume,Volume types and Longview related methods/functions
  go.mod
  go.work.sum
  k8s/go.mod
  test/integration/instances_test.go
  test/unit/fixtures/longview_client_single.json
  test/unit/fixtures/longview_clients_list.json
  test/unit/fixtures/longview_plan.json
  test/unit/fixtures/longview_subscription_get.json
  test/unit/fixtures/longview_subscriptions_list.json
  test/unit/fixtures/volume_attach.json
  test/unit/fixtures/volume_create.json
  test/unit/fixtures/volume_get.json
  test/unit/fixtures/volume_types_list.json
  test/unit/fixtures/volume_update.json
  test/unit/fixtures/volumes_list.json
  test/unit/longview_subscriptions_test.go
  test/unit/longview_test.go
  test/unit/volume_test.go
  test/unit/volume_types_test.go
Labels: testing

#656 test: Add domain and domain record unit test coverage
  go.work.sum
  test/unit/domain_test.go
  test/unit/domainrecord_test.go
  test/unit/fixtures/domain_create.json
  test/unit/fixtures/domain_get.json
  test/unit/fixtures/domain_get_domainzonefile.json
  test/unit/fixtures/domain_list.json
  test/unit/fixtures/domain_update.json
  test/unit/fixtures/domainrecord_create.json
  test/unit/fixtures/domainrecord_get.json
  test/unit/fixtures/domainrecord_list.json
  test/unit/fixtures/domainrecord_update.json
Labels: testing

#666 test: Update obj smoke test remove deprecated Cluster variable
  test/integration/fixtures/TestObjectStorageBuckets_List.yaml
  test/integration/object_storage_buckets_test.go
Labels: testing

#665 Allow to enable LKE APL
  lke_clusters.go
  test/integration/fixtures/TestLKECluster_APLEnabled.yaml
  test/integration/lke_clusters_test.go
Labels: new-feature

#673 Add unit test coverage for VPC related methods/functions
  test/unit/fixtures/vpc_create.json
  test/unit/fixtures/vpc_get.json
  test/unit/fixtures/vpc_ips_list.json
  test/unit/fixtures/vpc_list.json
  test/unit/fixtures/vpc_specific_ips_list.json
  test/unit/fixtures/vpc_subnet_create.json
  test/unit/fixtures/vpc_subnet_get.json
  test/unit/fixtures/vpc_subnet_update.json
  test/unit/fixtures/vpc_subnets_list.json
  test/unit/fixtures/vpc_update.json
  test/unit/vpc_ips_test.go
  test/unit/vpc_subnets_test.go
  test/unit/vpc_test.go
Labels: testing

#670 Add unit test coverage for Network related methods/functions
  test/unit/fixtures/network_ip_address_get.json
  test/unit/fixtures/network_ip_addresses_list.json
  test/unit/fixtures/network_ipv6_pools_get.json
  test/unit/fixtures/network_ipv6_pools_list.json
  test/unit/fixtures/network_ipv6_ranges_create.json
  test/unit/fixtures/network_ipv6_ranges_get.json
  test/unit/fixtures/network_ipv6_ranges_list.json
  test/unit/fixtures/network_reserved_ips.json
  test/unit/fixtures/network_reserved_ips_get.json
  test/unit/fixtures/network_reserved_ips_list.json
  test/unit/network_ips_test.go
  test/unit/network_ipv6_pools_test.go
  test/unit/network_ranges_test.go
  test/unit/network_reserved_ips_test.go
Labels: testing

#682 Add unit test coverage for Nodebalancers related methods/functions
  test/unit/fixtures/nodebalancer_config_create.json
  test/unit/fixtures/nodebalancer_config_get.json
  test/unit/fixtures/nodebalancer_config_list.json
  test/unit/fixtures/nodebalancer_config_rebuild.json
  test/unit/fixtures/nodebalancer_config_update.json
  test/unit/fixtures/nodebalancer_create.json
  test/unit/fixtures/nodebalancer_firewall_list.json
  test/unit/fixtures/nodebalancer_get.json
  test/unit/fixtures/nodebalancer_node_create.json
  test/unit/fixtures/nodebalancer_node_list.json
  test/unit/fixtures/nodebalancer_node_update.json
  test/unit/fixtures/nodebalancer_stats_get.json
  test/unit/fixtures/nodebalancer_update.json
  test/unit/fixtures/nodebalancers_list.json
  test/unit/fixtures/nodebalancers_types_list.json
  test/unit/nodebalancer_config_test.go
  test/unit/nodebalancer_firewalls_test.go
  test/unit/nodebalancer_node_test.go
  test/unit/nodebalancer_stats_test.go
  test/unit/nodebalancer_test.go
  test/unit/nodebalancer_types_test.go
Labels: testing

#676 Support LKE tier version
  lke_clusters.go
  test/integration/fixtures/TestLKETierVersion_ListAndGet.yaml
  test/integration/lke_clusters_test.go
Labels: new-feature

#684 Remove LKE ACL LA notices
  lke_clusters_control_plane.go
Labels: documentation

#683 Add unit test coverage for Object Storage and LKE related methods/functions
  test/unit/fixtures/lke_cluster_apl.json
  test/unit/fixtures/lke_cluster_control_plane_acl_get.json
  test/unit/fixtures/lke_cluster_control_plane_acl_update.json
  test/unit/fixtures/lke_cluster_create.json
  test/unit/fixtures/lke_cluster_dashboard.json
  test/unit/fixtures/lke_cluster_get.json
  test/unit/fixtures/lke_cluster_kubeconfig.json
  test/unit/fixtures/lke_cluster_list.json
  test/unit/fixtures/lke_cluster_pool_create.json
  test/unit/fixtures/lke_cluster_pool_get.json
  test/unit/fixtures/lke_cluster_pool_list.json
  test/unit/fixtures/lke_cluster_pool_update.json
  test/unit/fixtures/lke_cluster_regenerate.json
  test/unit/fixtures/lke_cluster_update.json
  test/unit/fixtures/lke_node_pool_create.json
  test/unit/fixtures/lke_node_pool_get.json
  test/unit/fixtures/lke_node_pool_list.json
  test/unit/fixtures/lke_node_pool_update.json
  test/unit/fixtures/lke_types_list.json
  test/unit/fixtures/object_storage_bucket_access_get.json
  test/unit/fixtures/object_storage_bucket_cert.json
  test/unit/fixtures/object_storage_bucket_contents.json
  test/unit/fixtures/object_storage_bucket_create.json
  test/unit/fixtures/object_storage_bucket_get.json
  test/unit/fixtures/object_storage_bucket_list.json
  test/unit/fixtures/object_storage_cluster_get.json
  test/unit/fixtures/object_storage_cluster_list.json
  test/unit/fixtures/object_storage_endpoints_list.json
  test/unit/fixtures/object_storage_key_create.json
  test/unit/fixtures/object_storage_key_get.json
  test/unit/fixtures/object_storage_key_list.json
  test/unit/fixtures/object_storage_key_list_by_region.json
  test/unit/fixtures/object_storage_key_update.json
  test/unit/fixtures/object_storage_object_acl_get.json
  test/unit/fixtures/object_storage_object_acl_update.json
  test/unit/fixtures/object_storage_object_url_create.json
  test/unit/lke_cluster_control_plane_acl_test.go
  test/unit/lke_cluster_pool_test.go
  test/unit/lke_clusters_test.go
  test/unit/lke_node_pools_test.go
  test/unit/lke_types_test.go
  test/unit/object_storage_bucket_cert_test.go
  test/unit/object_storage_bucket_test.go
  test/unit/object_storage_cluster_test.go
  test/unit/object_storage_endpoint_test.go
  test/unit/object_storage_key_test.go
  test/unit/object_storage_object_test.go
Labels: testing

#687 Add images unit test coverage
  test/unit/fixtures/image_create.json
  test/unit/fixtures/image_get.json
  test/unit/fixtures/image_update.json
  test/unit/fixtures/image_upload.json
  test/unit/fixtures/images_list.json
  test/unit/images_test.go
Labels: testing
